# Generated by Django 5.0.6 on 2024-06-04 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='ChambreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
            ],
        ),
        migrations.CreateModel(
            name='HostelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hostels/')),
            ],
        ),
        migrations.RenameField(
            model_name='chambre',
            old_name='titre',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='chambre',
            old_name='nombre_etoiles',
            new_name='nombre_lits',
        ),
        migrations.RenameField(
            model_name='publications',
            old_name='auteur',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='utilisateur',
            new_name='user',
        ),
        migrations.AddField(
            model_name='chambre',
            name='category',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='chambre',
            name='m2',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='prix',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='chambre',
            name='rating',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='publications',
            name='date_publication',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='publications',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publications/'),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default='Blablabla', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services-img/'),
        ),
        migrations.AddField(
            model_name='user',
            name='adresse_mail',
            field=models.EmailField(default='example@mail.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='numero_tel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='services-icons/'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BackApp.avataruser'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackApp.chambreimage'),
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nombre_chambres', models.IntegerField()),
                ('chambres', models.ManyToManyField(related_name='hostels', to='BackApp.chambre')),
                ('service', models.ManyToManyField(related_name='hostels', to='BackApp.service')),
                ('image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BackApp.hostelimage')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('rating', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Temoignage',
        ),
    ]
