# Generated by Django 5.0.6 on 2024-06-04 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0002_avataruser_chambreimage_hostelimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('rating', models.IntegerField()),
                ('image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BackApp.hostelimage')),
            ],
        ),
    ]
