# Generated by Django 5.0.6 on 2024-06-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0003_homebanner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publications',
            new_name='Publication',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='galerie/'),
        ),
    ]
