# Generated by Django 5.0.6 on 2024-06-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0005_remove_user_mail_alter_testimonial_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adresse_mail',
        ),
    ]
