# Generated by Django 5.0.6 on 2024-06-04 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0006_remove_user_adresse_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackApp.role'),
        ),
    ]
