# Generated by Django 5.0.6 on 2024-06-04 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='BackApp.avataruser'),
        ),
    ]
