# Generated by Django 5.0.6 on 2024-06-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='nom',
        ),
    ]
