# Generated by Django 5.0.6 on 2024-06-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0010_remove_role_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
    ]
