# Generated by Django 5.0.6 on 2024-06-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0012_alter_user_avatar_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelimage',
            name='nom',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='nombre_lits',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='rating',
            field=models.IntegerField(default='0'),
        ),
    ]
