# Generated by Django 5.0.6 on 2024-06-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0014_remove_hostel_nombre_chambres_remove_hostelimage_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='rating',
            field=models.IntegerField(default='0'),
        ),
    ]
