# Generated by Django 5.0.6 on 2024-06-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0016_heroslide_delete_homebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hostels_backgrounds/'),
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='nom',
            field=models.CharField(default='', max_length=220),
        ),
    ]
