# Generated by Django 5.0.6 on 2024-06-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0018_heroslide_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='title',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_one',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_second',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='rating',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle',
            field=models.CharField(default='', max_length=200),
        ),
    ]
