# Generated by Django 5.0.6 on 2024-06-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0019_remove_heroslide_title_heroslide_title_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
