# Generated by Django 5.0.6 on 2024-06-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0020_heroslide_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heroslide',
            old_name='title_second',
            new_name='title_two',
        ),
    ]
