# Generated by Django 5.0.6 on 2024-06-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0022_remove_heroslide_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='background_image',
        ),
    ]
