# Generated by Django 5.0.6 on 2024-06-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0023_remove_hostel_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='nbre_chambres',
            field=models.IntegerField(default='0'),
        ),
    ]
