# Generated by Django 5.0.6 on 2024-06-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0025_sectionmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='image',
        ),
        migrations.AddField(
            model_name='hostel',
            name='images',
            field=models.ManyToManyField(related_name='hostels', to='BackApp.hostelimage'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='nbre_chambres',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
