# Generated by Django 5.0.6 on 2024-06-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0026_remove_hostel_image_hostel_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
