# Generated by Django 5.0.6 on 2024-06-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0027_hostel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
