# Generated by Django 5.0.6 on 2024-06-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0029_heroslide_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='chambres',
            field=models.ManyToManyField(blank=True, related_name='hostels', to='BackApp.chambre'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='hostels', to='BackApp.hostelimage'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='hostels', to='BackApp.service'),
        ),
    ]
