# Generated by Django 5.0.6 on 2024-06-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0030_alter_hostel_chambres_alter_hostel_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
