# Generated by Django 5.0.6 on 2024-06-08 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0031_roomsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='hostel_nom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BackApp.hostel'),
        ),
        migrations.AddField(
            model_name='chambreimage',
            name='name',
            field=models.CharField(default='', max_length=220),
        ),
    ]
