# Generated by Django 5.0.6 on 2024-06-08 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0032_chambre_hostel_nom_chambreimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='hostel_nom',
            field=models.ForeignKey(default='Hostel One', on_delete=django.db.models.deletion.CASCADE, to='BackApp.hostel'),
        ),
    ]
