# Generated by Django 5.0.6 on 2024-06-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0033_alter_chambre_hostel_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chambre',
            old_name='nom',
            new_name='name',
        ),
    ]
