# Generated by Django 5.0.6 on 2024-06-08 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0035_alter_chambre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BackApp.chambreimage'),
        ),
    ]
