# Generated by Django 5.0.6 on 2024-06-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0036_alter_chambre_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='image',
        ),
        migrations.AddField(
            model_name='chambre',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='BackApp.chambreimage'),
        ),
    ]
